using Containervervoer.Classes.Enumerations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
//using Containervervoer.Classes;

namespace Containervervoer.Classes
{
    public class TestClass
    {
        public List<Container> Setup()
        {
            //Ship ship = new Ship(3, 2);

            List<Container> containers = new List<Container>
            {
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 6000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Cooled, 10000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Valuable, 5000),
                new Container(ContainerType.Normal, 12000),
                new Container(ContainerType.Normal, 6000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 7000),
                new Container(ContainerType.Cooled, 10000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Cooled, 4100),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Cooled, 4200),
                new Container(ContainerType.Normal, 6000),
                new Container(ContainerType.Normal, 12000),
                new Container(ContainerType.Cooled, 10000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 6000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Cooled, 10000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Cooled, 5000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 6000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 7000),
                new Container(ContainerType.Cooled, 10000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4100),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4200),
                new Container(ContainerType.Normal, 6000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Cooled, 10000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4300),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 7000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Cooled, 4000),
                new Container(ContainerType.Normal, 6000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Cooled, 10000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 5000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 6000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 7000),
                new Container(ContainerType.Cooled, 10000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Cooled, 4100),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Valuable, 4200),
                new Container(ContainerType.Normal, 6000),
                new Container(ContainerType.Normal, 12000),
                new Container(ContainerType.Cooled, 10000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Valuable, 4300),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 7000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Valuable, 12000),
                new Container(ContainerType.Normal, 6000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Cooled, 10000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 12000),
                new Container(ContainerType.Normal, 5000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 6000),
                new Container(ContainerType.Normal, 12000),
                new Container(ContainerType.Normal, 7000),
                new Container(ContainerType.Cooled, 10000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4100),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4200),
                new Container(ContainerType.Normal, 6000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Cooled, 10000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4300),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 7000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 12000),
                new Container(ContainerType.Normal, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 6000),
                new Container(ContainerType.Normal, 12000),
                new Container(ContainerType.Cooled, 10000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Valuable, 5000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 6000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 7000),
                new Container(ContainerType.Cooled, 10000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4100),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4200),
                new Container(ContainerType.Normal, 6000),
                new Container(ContainerType.Normal, 12000),
                new Container(ContainerType.Cooled, 10000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Valuable, 4300),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 7000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 6000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Cooled, 10000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 5000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 6000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 7000),
                new Container(ContainerType.Cooled, 10000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Valuable, 4100),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Valuable, 4200),
                new Container(ContainerType.Normal, 6000),
                new Container(ContainerType.Normal, 12000),
                new Container(ContainerType.Cooled, 10000),
                new Container(ContainerType.Cooled, 12000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Cooled, 4300),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 4000),
                new Container(ContainerType.Normal, 7000),
                new Container(ContainerType.Cooled, 10000)
            };

            //ship.CheckPossibilityForSolution(containers);

             return containers;
        }



    }

    
}
